// The AI providers a project can store credentials for. Backs the config UI and
// bounds the `provider` value on a credential. This list mirrors the model providers
// Mastra's model router can resolve (its bundled models.dev registry): the runtime
// passes the stored key as { providerId, modelId, apiKey } and Mastra resolves the
// endpoint. For openai/anthropic/google the native provider SDK is used; every other
// entry is addressed as an OpenAI-compatible endpoint whose base URL comes from the
// registry, so no base URL is asked for. `openai-compatible` is the catch-all for a
// provider not in the registry — it has no fixed endpoint, so the UI asks for one.
//
// The major providers are listed first; the rest follow alphabetically.

export interface ProviderMeta {
  key: string;
  label: string;
  requiresBaseUrl: boolean;
}

export const AI_PROVIDERS: ProviderMeta[] = [
  { key: 'openai', label: 'OpenAI', requiresBaseUrl: false },
  { key: 'anthropic', label: 'Anthropic', requiresBaseUrl: false },
  { key: 'google', label: 'Google (Gemini)', requiresBaseUrl: false },
  { key: 'xai', label: 'xAI (Grok)', requiresBaseUrl: false },
  { key: 'mistral', label: 'Mistral', requiresBaseUrl: false },
  { key: 'groq', label: 'Groq', requiresBaseUrl: false },
  { key: 'deepseek', label: 'DeepSeek', requiresBaseUrl: false },
  { key: 'cerebras', label: 'Cerebras', requiresBaseUrl: false },
  { key: 'perplexity', label: 'Perplexity', requiresBaseUrl: false },
  { key: 'togetherai', label: 'Together AI', requiresBaseUrl: false },
  { key: 'deepinfra', label: 'Deep Infra', requiresBaseUrl: false },
  { key: 'openrouter', label: 'OpenRouter', requiresBaseUrl: false },
  { key: 'vercel', label: 'Vercel AI Gateway', requiresBaseUrl: false },
  { key: 'abacus', label: 'Abacus', requiresBaseUrl: false },
  { key: 'alibaba', label: 'Alibaba', requiresBaseUrl: false },
  { key: 'ambient', label: 'Ambient', requiresBaseUrl: false },
  { key: 'anyapi', label: 'AnyAPI', requiresBaseUrl: false },
  { key: 'auriko', label: 'Auriko', requiresBaseUrl: false },
  { key: 'bailing', label: 'Bailing', requiresBaseUrl: false },
  { key: 'baseten', label: 'Baseten', requiresBaseUrl: false },
  { key: 'berget', label: 'Berget.AI', requiresBaseUrl: false },
  { key: 'chutes', label: 'Chutes', requiresBaseUrl: false },
  { key: 'clarifai', label: 'Clarifai', requiresBaseUrl: false },
  { key: 'claudinio', label: 'Claudinio', requiresBaseUrl: false },
  { key: 'cortecs', label: 'Cortecs', requiresBaseUrl: false },
  { key: 'crof', label: 'CrofAI', requiresBaseUrl: false },
  { key: 'drun', label: 'D.Run (China)', requiresBaseUrl: false },
  { key: 'databricks', label: 'Databricks', requiresBaseUrl: false },
  { key: 'digitalocean', label: 'DigitalOcean', requiresBaseUrl: false },
  { key: 'dinference', label: 'DInference', requiresBaseUrl: false },
  { key: 'evroc', label: 'evroc', requiresBaseUrl: false },
  { key: 'fastrouter', label: 'FastRouter', requiresBaseUrl: false },
  { key: 'freemodel', label: 'FreeModel', requiresBaseUrl: false },
  { key: 'friendli', label: 'Friendli', requiresBaseUrl: false },
  { key: 'frogbot', label: 'FrogBot', requiresBaseUrl: false },
  { key: 'gmicloud', label: 'GMI Cloud', requiresBaseUrl: false },
  { key: 'helicone', label: 'Helicone', requiresBaseUrl: false },
  { key: 'huggingface', label: 'Hugging Face', requiresBaseUrl: false },
  { key: 'iflowcn', label: 'iFlow', requiresBaseUrl: false },
  { key: 'inception', label: 'Inception', requiresBaseUrl: false },
  { key: 'inceptron', label: 'Inceptron', requiresBaseUrl: false },
  { key: 'inference', label: 'Inference', requiresBaseUrl: false },
  { key: 'jiekou', label: 'Jiekou.AI', requiresBaseUrl: false },
  { key: 'kenari', label: 'Kenari', requiresBaseUrl: false },
  { key: 'kilo', label: 'Kilo Gateway', requiresBaseUrl: false },
  { key: 'lilac', label: 'Lilac', requiresBaseUrl: false },
  { key: 'llama', label: 'Llama', requiresBaseUrl: false },
  { key: 'llmgateway', label: 'LLM Gateway', requiresBaseUrl: false },
  { key: 'llmtr', label: 'LLMTR', requiresBaseUrl: false },
  { key: 'lmstudio', label: 'LMStudio', requiresBaseUrl: false },
  { key: 'longcat', label: 'LongCat', requiresBaseUrl: false },
  { key: 'lucidquery', label: 'LucidQuery', requiresBaseUrl: false },
  { key: 'meganova', label: 'Meganova', requiresBaseUrl: false },
  { key: 'minimax', label: 'MiniMax', requiresBaseUrl: false },
  { key: 'mixlayer', label: 'Mixlayer', requiresBaseUrl: false },
  { key: 'moark', label: 'Moark', requiresBaseUrl: false },
  { key: 'modelscope', label: 'ModelScope', requiresBaseUrl: false },
  { key: 'moonshotai', label: 'Moonshot AI', requiresBaseUrl: false },
  { key: 'morph', label: 'Morph', requiresBaseUrl: false },
  { key: 'nearai', label: 'NEAR AI Cloud', requiresBaseUrl: false },
  { key: 'nebius', label: 'Nebius Token Factory', requiresBaseUrl: false },
  { key: 'neon', label: 'Neon', requiresBaseUrl: false },
  { key: 'neuralwatt', label: 'Neuralwatt', requiresBaseUrl: false },
  { key: 'nova', label: 'Nova', requiresBaseUrl: false },
  { key: 'nvidia', label: 'Nvidia', requiresBaseUrl: false },
  { key: 'opencode', label: 'OpenCode Zen', requiresBaseUrl: false },
  { key: 'orcarouter', label: 'OrcaRouter', requiresBaseUrl: false },
  { key: 'ovhcloud', label: 'OVHcloud AI Endpoints', requiresBaseUrl: false },
  { key: 'poe', label: 'Poe', requiresBaseUrl: false },
  { key: 'poolside', label: 'Poolside', requiresBaseUrl: false },
  { key: 'requesty', label: 'Requesty', requiresBaseUrl: false },
  { key: 'sakana', label: 'Sakana AI', requiresBaseUrl: false },
  { key: 'sarvam', label: 'Sarvam AI', requiresBaseUrl: false },
  { key: 'scaleway', label: 'Scaleway', requiresBaseUrl: false },
  { key: 'siliconflow', label: 'SiliconFlow', requiresBaseUrl: false },
  { key: 'stackit', label: 'STACKIT', requiresBaseUrl: false },
  { key: 'stepfun', label: 'StepFun', requiresBaseUrl: false },
  { key: 'subconscious', label: 'Subconscious', requiresBaseUrl: false },
  { key: 'submodel', label: 'Submodel', requiresBaseUrl: false },
  { key: 'synthetic', label: 'Synthetic', requiresBaseUrl: false },
  { key: 'tinfoil', label: 'Tinfoil', requiresBaseUrl: false },
  { key: 'trustedrouter', label: 'TrustedRouter', requiresBaseUrl: false },
  { key: 'upstage', label: 'Upstage', requiresBaseUrl: false },
  { key: 'vivgrid', label: 'Vivgrid', requiresBaseUrl: false },
  { key: 'vultr', label: 'Vultr', requiresBaseUrl: false },
  { key: 'wandb', label: 'Weights & Biases', requiresBaseUrl: false },
  { key: 'xiaomi', label: 'Xiaomi', requiresBaseUrl: false },
  { key: 'xpersona', label: 'Xpersona', requiresBaseUrl: false },
  { key: 'zai', label: 'Z.AI', requiresBaseUrl: false },
  { key: 'zeldoc', label: 'Zeldoc', requiresBaseUrl: false },
  { key: 'zenmux', label: 'ZenMux', requiresBaseUrl: false },
  { key: 'zhipuai', label: 'Zhipu AI', requiresBaseUrl: false },
  { key: '302ai', label: '302.AI', requiresBaseUrl: false },
  { key: 'abliteration-ai', label: 'abliteration.ai', requiresBaseUrl: false },
  { key: 'ai-router', label: 'AI-ROUTER', requiresBaseUrl: false },
  { key: 'alibaba-cn', label: 'Alibaba (China)', requiresBaseUrl: false },
  { key: 'alibaba-coding-plan', label: 'Alibaba Coding Plan', requiresBaseUrl: false },
  { key: 'alibaba-coding-plan-cn', label: 'Alibaba Coding Plan (China)', requiresBaseUrl: false },
  { key: 'alibaba-token-plan', label: 'Alibaba Token Plan', requiresBaseUrl: false },
  { key: 'alibaba-token-plan-cn', label: 'Alibaba Token Plan (China)', requiresBaseUrl: false },
  { key: 'atomic-chat', label: 'Atomic Chat', requiresBaseUrl: false },
  { key: 'blueclaw', label: 'Blue Claw', requiresBaseUrl: false },
  { key: 'cloudferro-sherlock', label: 'CloudFerro Sherlock', requiresBaseUrl: false },
  { key: 'cloudflare-workers-ai', label: 'Cloudflare Workers AI', requiresBaseUrl: false },
  { key: 'crossmodel', label: 'CrossModel', requiresBaseUrl: false },
  { key: 'daoxe', label: 'DaoXE', requiresBaseUrl: false },
  { key: 'ebcloud', label: 'EBCloud', requiresBaseUrl: false },
  { key: 'empiriolabs', label: 'EmpirioLabs AI', requiresBaseUrl: false },
  { key: 'fireworks-ai', label: 'Fireworks AI', requiresBaseUrl: false },
  { key: 'github-models', label: 'GitHub Models', requiresBaseUrl: false },
  { key: 'hpc-ai', label: 'HPC-AI', requiresBaseUrl: false },
  { key: 'inferx', label: 'InferX', requiresBaseUrl: false },
  { key: 'io-net', label: 'IO.NET', requiresBaseUrl: false },
  { key: 'kimi-for-coding', label: 'Kimi For Coding', requiresBaseUrl: false },
  { key: 'kuae-cloud-coding-plan', label: 'KUAE Cloud Coding Plan', requiresBaseUrl: false },
  { key: 'lynkr', label: 'Lynkr', requiresBaseUrl: false },
  { key: 'meta', label: 'Meta', requiresBaseUrl: false },
  { key: 'minimax-cn', label: 'MiniMax (minimaxi.com)', requiresBaseUrl: false },
  {
    key: 'minimax-cn-coding-plan',
    label: 'MiniMax Token Plan (minimaxi.com)',
    requiresBaseUrl: false,
  },
  { key: 'minimax-coding-plan', label: 'MiniMax Token Plan (minimax.io)', requiresBaseUrl: false },
  { key: 'model-oracle-ai', label: 'Model Oracle AI', requiresBaseUrl: false },
  { key: 'moonshotai-cn', label: 'Moonshot AI (China)', requiresBaseUrl: false },
  { key: 'nano-gpt', label: 'NanoGPT', requiresBaseUrl: false },
  { key: 'novita-ai', label: 'NovitaAI', requiresBaseUrl: false },
  { key: 'ollama-cloud', label: 'Ollama Cloud', requiresBaseUrl: false },
  { key: 'opencode-go', label: 'OpenCode Go', requiresBaseUrl: false },
  { key: 'perplexity-agent', label: 'Perplexity Agent', requiresBaseUrl: false },
  { key: 'pioneer', label: 'Pioneer', requiresBaseUrl: false },
  { key: 'privatemode-ai', label: 'Privatemode AI', requiresBaseUrl: false },
  { key: 'qihang-ai', label: 'QiHang', requiresBaseUrl: false },
  { key: 'qiniu-ai', label: 'Qiniu', requiresBaseUrl: false },
  { key: 'regolo-ai', label: 'Regolo AI', requiresBaseUrl: false },
  { key: 'routing-run', label: 'routing.run', requiresBaseUrl: false },
  { key: 'siliconflow-cn', label: 'SiliconFlow (China)', requiresBaseUrl: false },
  { key: 'snowflake-cortex', label: 'Snowflake Cortex', requiresBaseUrl: false },
  { key: 'stepfun-ai', label: 'StepFun (Global)', requiresBaseUrl: false },
  { key: 'stepfun-ai-step-plan', label: 'StepFun Step Plan (Global)', requiresBaseUrl: false },
  { key: 'stepfun-step-plan', label: 'StepFun Step Plan (China)', requiresBaseUrl: false },
  { key: 'tencent-coding-plan', label: 'Tencent Coding Plan (China)', requiresBaseUrl: false },
  { key: 'tencent-token-plan', label: 'Tencent Token Plan', requiresBaseUrl: false },
  { key: 'tencent-tokenhub', label: 'Tencent TokenHub', requiresBaseUrl: false },
  { key: 'the-grid-ai', label: 'The Grid AI', requiresBaseUrl: false },
  { key: 'umans-ai', label: 'Umans AI', requiresBaseUrl: false },
  { key: 'umans-ai-coding-plan', label: 'Umans AI Coding Plan', requiresBaseUrl: false },
  { key: 'unorouter', label: 'UnoRouter', requiresBaseUrl: false },
  { key: 'wafer.ai', label: 'Wafer', requiresBaseUrl: false },
  { key: 'xiaomi-token-plan-ams', label: 'Xiaomi Token Plan (Europe)', requiresBaseUrl: false },
  { key: 'xiaomi-token-plan-cn', label: 'Xiaomi Token Plan (China)', requiresBaseUrl: false },
  { key: 'xiaomi-token-plan-sgp', label: 'Xiaomi Token Plan (Singapore)', requiresBaseUrl: false },
  { key: 'zai-coding-plan', label: 'Z.AI Coding Plan', requiresBaseUrl: false },
  { key: 'zenifra', label: 'Zenifra', requiresBaseUrl: false },
  { key: 'zhipuai-coding-plan', label: 'Zhipu AI Coding Plan', requiresBaseUrl: false },
  { key: 'openai-compatible', label: 'OpenAI-compatible (custom)', requiresBaseUrl: true },
];
