import {
  Zap,
  Check,
  CheckCheck,
  CheckCircle,
  X,
  XCircle,
  ThumbsUp,
  ThumbsDown,
  Flag,
  Star,
  Heart,
  Bookmark,
  Bell,
  BellOff,
  Clock,
  Timer,
  Hourglass,
  Calendar,
  CalendarClock,
  Play,
  Pause,
  Square,
  SkipForward,
  Rocket,
  Send,
  Mail,
  MessageSquare,
  MessageCircle,
  Reply,
  Share2,
  Megaphone,
  Archive,
  ArchiveRestore,
  Inbox,
  Ban,
  AlertTriangle,
  AlertCircle,
  Info,
  HelpCircle,
  Bug,
  Wrench,
  Hammer,
  Settings,
  Sliders,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  ShieldCheck,
  Shield,
  ShieldAlert,
  GitMerge,
  GitBranch,
  GitPullRequest,
  GitCommitHorizontal,
  Code,
  Terminal,
  Tag,
  Tags,
  Bookmark as BookmarkIcon,
  Paperclip,
  Link,
  Pin,
  User,
  UserPlus,
  UserCheck,
  UserX,
  Users,
  Crown,
  Award,
  Trophy,
  Target,
  Flame,
  Sparkles,
  Wand2,
  Lightbulb,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  ArrowLeft,
  ArrowUpCircle,
  ArrowDownCircle,
  ChevronsUp,
  ChevronsDown,
  RefreshCw,
  RotateCcw,
  Repeat,
  Undo2,
  Redo2,
  Trash2,
  Trash,
  Copy,
  ClipboardCheck,
  ClipboardList,
  FileText,
  File,
  FilePlus,
  FileCheck,
  Folder,
  FolderCheck,
  Package,
  PackageCheck,
  Truck,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Percent,
  Gauge,
  Activity,
  TrendingUp,
  TrendingDown,
  BarChart,
  PieChart,
  Layers,
  List,
  ListChecks,
  Kanban,
  Filter,
  Search,
  Bolt,
  Power,
  Plug,
  Wifi,
  Cloud,
  CloudUpload,
  CloudDownload,
  Download,
  Upload,
  Save,
  Database,
  Server,
  Globe,
  MapPin,
  Compass,
  Home,
  Building,
  Briefcase,
  Coffee,
  Smile,
  Frown,
  Circle,
  CircleDot,
  Dot,
  Plus,
  Minus,
  Equal,
  Hash,
  AtSign,
  Snowflake,
  Sun,
  Moon,
  type LucideIcon,
} from 'lucide-react';

// Curated set of icons an action can display. The key is stored on the action
// (project_action.icon) and resolved to a component here. Order is the order
// shown in the picker; keys are what the picker's search matches against.
export const ACTION_ICONS: Record<string, LucideIcon> = {
  zap: Zap,
  bolt: Bolt,
  check: Check,
  'check-check': CheckCheck,
  'check-circle': CheckCircle,
  x: X,
  'x-circle': XCircle,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  flag: Flag,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  bell: Bell,
  'bell-off': BellOff,
  clock: Clock,
  timer: Timer,
  hourglass: Hourglass,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  play: Play,
  pause: Pause,
  stop: Square,
  'skip-forward': SkipForward,
  rocket: Rocket,
  send: Send,
  mail: Mail,
  message: MessageSquare,
  'message-circle': MessageCircle,
  reply: Reply,
  share: Share2,
  megaphone: Megaphone,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  inbox: Inbox,
  ban: Ban,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  info: Info,
  help: HelpCircle,
  bug: Bug,
  wrench: Wrench,
  hammer: Hammer,
  settings: Settings,
  sliders: Sliders,
  eye: Eye,
  'eye-off': EyeOff,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  'shield-check': ShieldCheck,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'git-merge': GitMerge,
  'git-branch': GitBranch,
  'git-pull-request': GitPullRequest,
  'git-commit': GitCommitHorizontal,
  code: Code,
  terminal: Terminal,
  tag: Tag,
  tags: Tags,
  bookmark2: BookmarkIcon,
  paperclip: Paperclip,
  link: Link,
  pin: Pin,
  user: User,
  'user-plus': UserPlus,
  'user-check': UserCheck,
  'user-x': UserX,
  users: Users,
  crown: Crown,
  award: Award,
  trophy: Trophy,
  target: Target,
  flame: Flame,
  sparkles: Sparkles,
  wand: Wand2,
  lightbulb: Lightbulb,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up-circle': ArrowUpCircle,
  'arrow-down-circle': ArrowDownCircle,
  'chevrons-up': ChevronsUp,
  'chevrons-down': ChevronsDown,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  repeat: Repeat,
  undo: Undo2,
  redo: Redo2,
  trash: Trash2,
  'trash-2': Trash,
  copy: Copy,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'file-text': FileText,
  file: File,
  'file-plus': FilePlus,
  'file-check': FileCheck,
  folder: Folder,
  'folder-check': FolderCheck,
  package: Package,
  'package-check': PackageCheck,
  truck: Truck,
  cart: ShoppingCart,
  'credit-card': CreditCard,
  dollar: DollarSign,
  percent: Percent,
  gauge: Gauge,
  activity: Activity,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'bar-chart': BarChart,
  'pie-chart': PieChart,
  layers: Layers,
  list: List,
  'list-checks': ListChecks,
  kanban: Kanban,
  filter: Filter,
  search: Search,
  power: Power,
  plug: Plug,
  wifi: Wifi,
  cloud: Cloud,
  'cloud-upload': CloudUpload,
  'cloud-download': CloudDownload,
  download: Download,
  upload: Upload,
  save: Save,
  database: Database,
  server: Server,
  globe: Globe,
  'map-pin': MapPin,
  compass: Compass,
  home: Home,
  building: Building,
  briefcase: Briefcase,
  coffee: Coffee,
  smile: Smile,
  frown: Frown,
  circle: Circle,
  'circle-dot': CircleDot,
  dot: Dot,
  plus: Plus,
  minus: Minus,
  equal: Equal,
  hash: Hash,
  'at-sign': AtSign,
  snowflake: Snowflake,
  sun: Sun,
  moon: Moon,
};

// The icon shown when an action has no icon set or an unknown key.
export const DEFAULT_ACTION_ICON: LucideIcon = Zap;

export const ACTION_ICON_KEYS = Object.keys(ACTION_ICONS);

// Resolves an action's stored icon key to a component, falling back to the
// default for empty or unknown keys.
export function actionIcon(key: string | undefined | null): LucideIcon {
  return (key && ACTION_ICONS[key]) || DEFAULT_ACTION_ICON;
}
